services:
  haproxy:
    image: haproxy:3.2-dev13
    container_name: haproxy
    ports:
      - "27018:27018"
      - "8404:8404"
    depends_on:
      mongodb1:
        condition: service_healthy
      mongodb2:
        condition: service_healthy
      mongodb3:
        condition: service_healthy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: unless-stopped
    networks:
      connet:
        ipv4_address: 192.168.22.16

networks:
  connet:
    external: true
